= Sistema de Gerenciamento de Biblioteca
 
== Sobre o Projeto
O Sistema de Gerenciamento de Biblioteca foi desenvolvido para facilitar o
processo de empréstimo, devolução e gerenciamento de livros em uma
biblioteca. Através da aplicação, é possível gerenciar empréstimos de livros,
disponibilidade de exemplares, cadastro de usuários e gerar relatórios de
atividades. O sistema visa melhorar a experiência do usuário e otimizar a
administração da biblioteca, garantindo uma gestão eficiente e eficaz.

== Recursos
* **Cadastro e gerenciamento de livros** com informações detalhadas
(título, autor, ISBN, etc.).
* **Criação e modificação de empréstimos** de livros, com opções de data
de empréstimo e devolução.
* **Visualização da disponibilidade dos livros** em tempo real.
* **Geração de relatórios** de empréstimos, devoluções e multas.
* **Notificação de usuários** sobre empréstimos e devoluções.
* **Sistema de login** e autenticação para administradores e usuários.

== Tecnologias Utilizadas

* *1. FrontEnd*
  ** *Angular*: Framework utilizado para o desenvolvimento da
  interface de usuário, permitindo uma aplicação interativa e
  responsiva.

* *2. Backend*
  ** *Spring Boot (Java):*: Framework utilizado para o desenvolvimento
  da API, que gerencia os empréstimos, os livros e os usuários.

* *3. Banco de Dados*
  ** *MySQL:*: Banco de dados relacional utilizado para armazenar
  informações sobre empréstimos, usuários e livros..

* *4. Autenticação*
  ** *JWT (JSON Web Tokens):*: Utilizado para garantir a segurança
  no processo de autenticação e autorização de usuários.

= Como Executar

* *1. Clone o Repositório*

Clone o repositório para o seu ambiente local com o comando:
[source,sh]
----
git clone https://github.com/usuario/sistema-biblioteca.git
----

* *2. Instale as Dependências do Frontend*

Navegue até o diretório do frontend e instale as dependências com npm:
[source,sh]
----
cd sistema-biblioteca/frontend
npm install
----


